### ISSUE TITLE
Serialization broken in 0.25.3

### ISSUE THREAD

**Issue by zstewar1** [dimforge/nalgebra#856]
nalgebra fails to build on v0.25.3 if feature `serde-serialize` is enabled.

This can be reproduced with a completely empty library project depending on nothing but nalgebra 0.25:

```shell
$ rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
$ cargo --version
cargo 1.51.0 (43b129a20 2021-03-16)
$ cat Cargo.toml 
[package]
name = "example"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
nalgebra = { version = "0.25", features = ["serde-serialize"] }
$ cat src/lib.rs
$ cargo build
   Compiling nalgebra v0.25.3
error[E0277]: the trait bound `Vec<N>: Serialize` is not satisfied
  --> /home/zstewart/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.25.3/src/base/vec_storage.rs:29:5
   |
29 |     data: Vec<N>,
   |     ^^^^ the trait `Serialize` is not implemented for `Vec<N>`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `Vec<N>: Deserialize<'_>` is not satisfied
  --> /home/zstewart/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.25.3/src/base/vec_storage.rs:29:5
   |
29 |     data: Vec<N>,
   |     ^^^^ the trait `Deserialize<'_>` is not implemented for `Vec<N>`
   |
   = note: required by `next_element`

error[E0277]: the trait bound `Vec<N>: Deserialize<'_>` is not satisfied
  --> /home/zstewart/.cargo/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.25.3/src/base/vec_storage.rs:29:5
   |
29 |     data: Vec<N>,
   |     ^^^^ the trait `Deserialize<'_>` is not implemented for `Vec<N>`
   |
   = note: required by `next_value`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `nalgebra`

To learn more, run the command again with --verbose.
```
