### ISSUE TITLE
Fails to build on rustc 0.13.0-nightly (34d680009 2014-12-22 00:12:47 +0000)

### ISSUE THREAD

**Issue by bfops** [dimforge/nalgebra#58]
```
src/traits/structure.rs:6:18: 6:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/traits/structure.rs:6 use std::slice::{Iter, IterMut};
                                           ^~~~
src/traits/structure.rs:6:24: 6:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/traits/structure.rs:6 use std::slice::{Iter, IterMut};
                                                 ^~~~~~~
src/structs/mat.rs:7:18: 7:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/mat.rs:7 use std::slice::{Iter, IterMut};
                                      ^~~~
src/structs/mat.rs:7:24: 7:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/mat.rs:7 use std::slice::{Iter, IterMut};
                                            ^~~~~~~
src/structs/quat.rs:8:18: 8:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/quat.rs:8 use std::slice::{Iter, IterMut};
                                       ^~~~
src/structs/quat.rs:8:24: 8:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/quat.rs:8 use std::slice::{Iter, IterMut};
                                             ^~~~~~~
src/structs/vec.rs:6:18: 6:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/vec.rs:6 use std::slice::{Iter, IterMut};
                                      ^~~~
src/structs/vec.rs:6:24: 6:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/vec.rs:6 use std::slice::{Iter, IterMut};
                                            ^~~~~~~
src/structs/spec/vec0.rs:2:18: 2:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/spec/vec0.rs:2 use std::slice::{Iter, IterMut};
                                            ^~~~
src/structs/spec/vec0.rs:2:24: 2:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/spec/vec0.rs:2 use std::slice::{Iter, IterMut};
                                                  ^~~~~~~
src/structs/pnt.rs:6:18: 6:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/pnt.rs:6 use std::slice::{Iter, IterMut};
                                      ^~~~
src/structs/pnt.rs:6:24: 6:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/pnt.rs:6 use std::slice::{Iter, IterMut};
                                            ^~~~~~~
src/structs/dvec.rs:7:18: 7:22 error: unresolved import `std::slice::Iter`. There is no `Iter` in `std::slice`
src/structs/dvec.rs:7 use std::slice::{Iter, IterMut};
                                       ^~~~
src/structs/dvec.rs:7:24: 7:31 error: unresolved import `std::slice::IterMut`. There is no `IterMut` in `std::slice`
src/structs/dvec.rs:7 use std::slice::{Iter, IterMut};
```
