### ISSUE TITLE
additional means of construction for constants

### ISSUE THREAD

**Issue by sed-i** [dimforge/nalgebra#1058]
This compiles with nalgebra 0.29.0:
```rust
const ZERO: Vector3<f64> = Vector3::new(0.0, 0.0, 0.0);
```

but these do not:
```rust
const ZERO: Vector3<f64> = Vector3::zeros();
const ZERO: Vector3<f64> = Vector3::from_row_slice(&[0.0, 0.0, 0.0]);

// error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
```

It would be handy if additional means of [construction](https://nalgebra.org/docs/user_guide/vectors_and_matrices/) (e.g. zeros) could be used for constants.

**Comment by Andlon** [comment]
Unfortunately the user guide has not yet been updated, but the macros `vector!` and `matrix!` should do what you want:

```rust
const ZERO: Vector3<f64> = vector![0.0, 0.0, 0.0];
```

Hope that helps!
